#!/usr/bin/env vesta
(load 'enyalios.ss)
(let ((kod (generate-code '(cond (< 3 4) "foo" (> 5 4) "bar" else "wut?") '() #t {} {}))
      (k0d (generate-code '(if (< 3 4) "foo" "wut?") '() #t {} {}))
      (fdout (open "8test.c" :write)))
    (write kod)
    (newline)
    (write k0d)
    (newline)
    (il->c (cadr kod) 0 fdout)
    (newline fdout)
    (newline fdout)
    (display "=====\n\n" fdout)
    (il->c (cadr k0d) 0 fdout)
    (close fdout))
