(define (count-down s)
    (lambda ()
        (if (<= s 0)
            0
            (begin
                (set! s (- s 1))
                (+ s 1)))))
(define f (count-down 20))
(define g (count-down 10))
(display (f))
(newline) 
(display (f))
(newline) 
(display (f))
(newline) 
(display (f))
(newline) 
(display (f))
(newline) 
(display (f))
(newline) 

(display (g))
(newline) 
(display (g))
(newline) 
(display (g))
(newline) 
(display (g))
(newline) 
(display (g))
(newline) 
(display (g))
(newline) 
