(define (assert v t m)
    (if (eq? v t)
        (display "%ASSERTION-TRUE: ")
        (display "%ASSERTION-FALSE: "))
    (display m)
    (display " ")
    (display v)
    (display " ")
    (display t)
    (newline))
