(define-syntax cond (else)
  ((_ else e1) e1) 
  ((_ e1 e2) (if e1 e2 #f))
  ((_ e1 e2 e3 ...) (if e1 e2 (cond e3 ...))))
(display (cond (< 3 4) 'yes (> 5 6) 'no else #f))
(newline)
(display (cond (> 5 6) 'no (< 3 4) 'yes else #f))
(newline)
(display (cond (> 5 6) 'no (< 4 3) 'nono else 'yes))
(newline)
